version: 0.1

phases:
  install:
    commands:
      - "wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip"
      - "unzip terraform_0.11.14_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
      - "chmod 755 /usr/local/bin/terraform"

  build:
    commands:
      - ls -l

  post_build:
    commands:
      # - echo terraform $TF_COMMAND completed on `date`
      - uptime
